site_name: Projeto de Machine Learning
site_url: https://example.com/
nav:
    - Intro: intro.md
    - 'Código': 
        - 'Part 1': code_part1.md
        - 'Part 2': code_part2.md
        - 'Part 3': code_part3.md

theme:
    name: mkdocs
    nav_style: dark