version: '3'

services:
  tensorflow:
    build: 
      context: .
      shm_size: '7gb'
    shm_size: '7gb'
    network_mode: 'host'
    privileged: true
    environment:
      - DISPLAY
    ports:
      - "8008:8888"
    volumes:
      - ./clip:/home/clip
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
